#!/bin/sh

# ff-loop (C) TVDiva, GPL

# Скрипт запускается в папке с видео файлами. В зависимости от имени файла, применяется фильтр.
# Имена файлов должны иметь следующий формат:
# NN-FILTER_NAME.mkv
# "FILTER_NAME" должно быть между символами "-" и "." и соответствовать одному из ключей в хеше FILTER

# "Россия 24", SAT, 720x576
# r24b1			"Россия 24". Размытие, одинарная полоса снизу
# r24b2			"Россия 24". Размытие, двойная полоса снизу
# r24b1t		"Россия 24". Размытие, одинарная полоса снизу и полоса сверху
# r24b2t		"Россия 24". Размытие, двойная полоса снизу и полоса сверху
# r24t			"Россия 24". Размытие, полоса сверху
# r24null   	"Россия 24", Без фильтров

# "Первый канал HD, SAT, 1920x1080
# c1l			Новости
# c1null		Новости. Без фильтров

# "Россия 1 HD, SAT, 1920x1080
# r1hdl			Новости
# r1hdnull		Новости. Без фильтров

# "Мир 24 HD, OF, 1920x1080
# m24l			Условно левая часть (самая удалённая)
# m24c1			Центр правая часть с одинарной обрезкой снизу
# m24c2			Центр с двойной обрезкой снизу

r24Blur="15"	# "Россия 24". Степень размытия
r24t="54"		# "Россия 24". Отступ сверху. Отношение высоты полного кадра к высоте полосы = 10.6667
r24b1="44"		# "Россия 24". Отступ снизу одинарный. Отношение высоты полного кадра к высоте полосы = 13.091
r24b2="68"		# "Россия 24". Отступ снизу двойной. Отношение высоты полного кадра к высоте полосы = 8.4706

c1Blur="25"			# Первый HD. Степень размытия
c1lc="200:978"		# Первый HD, новости. Координаты полосы
c1ls="1720:56"		# Первый HD, новости. Размер полосы

r1hdBlur="25"		# Россия 1 HD. Степень размытия
r1hdlc="142:973"	# Россия 1 HD, новости. Координаты полосы
r1hdls="1643:54"	# Россия 1 HD, новости. Размер полосы

declare -A FILTER=(
  [r24b1]="-pix_fmt yuv422p -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24b1:0:0[fg];[bg][fg]overlay=0:0"
  [r24b2]="-pix_fmt yuv422p -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24b2:0:0[fg];[bg][fg]overlay=0:0"
  [r24b1t]="-pix_fmt yuv422p -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24t-$r24b1:0:$r24t[fg];[bg][fg]overlay=0:$r24t"
  [r24b2t]="-pix_fmt yuv422p -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24t-$r24b2:0:$r24t[fg];[bg][fg]overlay=0:$r24t"
  [r24t]="-pix_fmt yuv422p -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24t:0:$r24t[fg];[bg][fg]overlay=0:$r24t"
  [r24null]="-pix_fmt yuv422p"
  [c1l]="-pix_fmt yuv422p -filter_complex [0:v]crop=$c1ls:$c1lc,boxblur=$c1Blur[fg];[0:v][fg]overlay=$c1lc[v] -map [v] -map 0:a"
  [c1null]="-pix_fmt yuv422p"
  [r1hdl]="-pix_fmt yuv422p -filter_complex [0:v]crop=$r1hdls:$r1hdlc,boxblur=$r1hdBlur[fg];[0:v][fg]overlay=$r1hdlc[v] -map [v] -map 0:a"
  [r1hdnull]="-pix_fmt yuv422p"
  [m24l]="-pix_fmt yuv422p -filter:v crop=1064:598:150:162,scale=1920:1080"
  [m24c1]="-pix_fmt yuv422p -filter:v crop=1712:962:104:0,scale=1920:1080"
  [m24c2]="-pix_fmt yuv422p -filter:v crop=1496:840:212:0,scale=1920:1080"
  )

FolderConverted="converted"
FolderSources="sources"

ls -1 *.{mkv,mp4,ts} 2>/dev/null | while read InFile
  do
	test -d "$FolderConverted" || mkdir -p "$FolderConverted"
	fName=$(echo "$InFile" | awk -F'-' '{print $2}' | awk -F'.' '{print $1}')
	if [[ ${FILTER[$fName]+_} ]] 
	  then
		Filter=${FILTER[$fName]}
		echo "Фильтр: $Filter"
		ffmpeg -nostdin -hide_banner -i "$InFile" $Filter -c:v huffyuv -c:a copy -y "$FolderConverted/$InFile"
		echo "ffmpeg exit code = $?"
		if [[ $? == 0 ]]
		  then
			test -d "$FolderSources" || mkdir -p "$FolderSources"
			mv "$InFile" "$FolderSources/$InFile"
		  fi
	else
	  echo "Нет такого фильтра: $fName, файл $InFile" | tee -a ff-loop.log
	fi
  done
