#!/bin/sh

# ff-loop (C) TVDiva, GPL

# Скрипт запускается в папке с видео файлами. В зависимости от имени файла, применяется фильтр.
# Имена файлов должны иметь следующий формат:
# NN-FILTER_NAME.mkv
# "FILTER_NAME" должно быть между символами "-" и "." и соответствовать одному из ключей в хеше FILTER

# null			Без фильтров с соотношением сторон 16/9

# "Россия 24", SAT, Height=576
# r24b1			Размытие, одинарная полоса снизу
# r24b2			Размытие, двойная полоса снизу
# r24b1t		Размытие, одинарная полоса снизу и полоса сверху
# r24b2t		Размытие, двойная полоса снизу и полоса сверху
# r24t			Размытие, полоса сверху

# "Россия 24", Yotube, Height=720
# r24hdb1		Размытие, одинарная полоса снизу
# r24hdb2		Размытие, двойная полоса снизу
# r24hdb1t		Размытие, одинарная полоса снизу и полоса сверху
# r24hdt		Размытие, полоса сверху

# "Первый канал" HD, SAT, 1920x1080
# c1l			Новости
# c1w			Полоса погоды в новостях
# c1lw			Одновременно c1l и c1w

# "Россия 1" HD, SAT, 1920x1080
# r1hdl			Новости
# r1hdm			Утро

# "Мир 24" HD, OF, 1920x1080
# m24l			Самая удалённая сцена.
# m24l2			Ещё более удалённая сцена.
# m24c1			Самая крупная центральная часть, Одинарная обрезка снизу.
# m24c2			Самая крупная центральная часть. Двойная обрезка снизу.
# m24r1			Правая часть. Одинарная обрезка снизу.
# m24r2			Правая часть. Двойная обрезка снизу.

# "Звезда" HD, OF, 1920x1080
# zl			Новости

r24Blur="15"		# "Россия 24". Степень размытия
# "Россия 24". Height=576
r24t="54"			# Отступ сверху. Отношение высоты полного кадра к высоте полосы = 10.6667
r24b1="44"			# Отступ снизу одинарный. Отношение высоты полного кадра к высоте полосы = 13.091
r24b2="68"			# Отступ снизу двойной. Отношение высоты полного кадра к высоте полосы = 8.4706

# "Россия 24". YouTube Height=720 (https://www.youtube.com/watch?v=8T9SFZDP60Q)
r24hdt="62"			# Отступ сверху. Отношение высоты полного кадра к высоте полосы = 11,6129
r24hdb1="56"		# Отступ снизу одинарный. Отношение высоты полного кадра к высоте полосы = 12,8571
r24hdb2="90"		# Отступ снизу двойной. Отношение высоты полного кадра к высоте полосы = 8

# Первый HD 1920x1080
c1Blur="25"			# Степень размытия
c1lc="200:978"		# Новости. Координаты полосы
c1ls="1720:56"		# Новости. Размер полосы
c1wc="202:904"		# Новости. Координаты полосы погоды
c1ws="1516:72"		# Новости. Размер полосы погоды

# Россия 1 HD 1920x1080
r1hdBlur="25"		# Степень размытия
r1hdlc="142:972"	# новости. Координаты полосы
r1hdls="1643:55"	# Новости. Размер полосы
r1hdmc="141:967"	# Утро. Координаты полосы
r1hdms="1646:66"	# Утро. Размер полосы

# Звезда HD 1920x1080
zBlur="25"			# Степень размытия
zc="92:966"			# Новости. Координаты полосы
zs="1744:62"		# Новости. Размер полосы

yuv422="-pix_fmt yuv422p"

declare -A FILTER=(
  [null]="$yuv422 -aspect 16:9"
  [r24b1]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24b1:0:0[fg];[bg][fg]overlay=0:0 -aspect 16:9"
  [r24b2]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24b2:0:0[fg];[bg][fg]overlay=0:0 -aspect 16:9"
  [r24b1t]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24t-$r24b1:0:$r24t[fg];[bg][fg]overlay=0:$r24t -aspect 16:9"
  [r24b2t]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24t-$r24b2:0:$r24t[fg];[bg][fg]overlay=0:$r24t -aspect 16:9"
  [r24t]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24t:0:$r24t[fg];[bg][fg]overlay=0:$r24t -aspect 16:9"
  [r24hdb1]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24hdb1:0:0[fg];[bg][fg]overlay=0:0 -aspect 16:9"
  [r24hdb2]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24hdb2:0:0[fg];[bg][fg]overlay=0:0 -aspect 16:9"
  [r24hdb1t]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24hdt-$r24hdb1:0:$r24hdt[fg];[bg][fg]overlay=0:$r24hdt -aspect 16:9"
  [r24hdb2t]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24hdt-$r24hdb2:0:$r24hdt[fg];[bg][fg]overlay=0:$r24hdt -aspect 16:9"
  [r24hdt]="$yuv422 -filter_complex [0:v]boxblur=$r24Blur[bg];[0:v]crop=iw:ih-$r24hdt:0:$r24hdt[fg];[bg][fg]overlay=0:$r24hdt -aspect 16:9"
  [c1l]="$yuv422 -filter_complex [0:v]crop=$c1ls:$c1lc,boxblur=$c1Blur[fg];[0:v][fg]overlay=$c1lc[v] -map [v] -map 0:a"
  [c1w]="$yuv422 -filter:v delogo=$c1wc:$c1ws"
  [c1lw]="$yuv422 -filter_complex [0:v]crop=$c1ls:$c1lc,boxblur=$c1Blur[fg];[0:v][fg]overlay=$c1lc[v] -map [v] -map 0:a"
  [c1lw]="$yuv422 -filter_complex [0:v]crop=$c1ls:$c1lc,boxblur=$c1Blur[fg];[0:v][fg]overlay=$c1lc,delogo=$c1wc:$c1ws[v] -map [v] -map 0:a"
  [r1hdl]="$yuv422 -filter:v delogo=$r1hdlc:$r1hdls"
  [r1hdm]="$yuv422 -filter:v delogo=$r1hdmc:$r1hdms"
  [m24l]="$yuv422 -filter:v crop=1134:638:150:142,scale=1920:1080"
  [m24l2]="$yuv422 -filter:v crop=944:530:276:210,scale=1920:1080"
  [m24c1]="$yuv422 -filter:v crop=1712:962:104:0,scale=1920:1080"
  [m24c2]="$yuv422 -filter:v crop=1496:840:212:0,scale=1920:1080"
  [m24r1]="$yuv422 -filter:v crop=1558:876:386:24,scale=1920:1080"
  [m24r2]="$yuv422 -filter:v crop=1406:814:514:24,scale=1920:1080"
  [zl]="$yuv422 -filter:v delogo=$zc:$zs"
  )

FolderConverted="converted"
FolderSources="sources"

ls -1 *.{mkv,mp4,ts} 2>/dev/null | while read InFile
  do
	test -d "$FolderConverted" || mkdir -p "$FolderConverted"
	fName=$(echo "$InFile" | awk -F'-' '{print $2}' | awk -F'.' '{print $1}')
	if [[ ${FILTER[$fName]+_} ]] 
	  then
		Filter=${FILTER[$fName]}
		echo "Фильтр: $Filter"
		ffmpeg -nostdin -hide_banner -i "$InFile" $Filter -c:v huffyuv -c:a copy -y "$FolderConverted/$InFile"
		echo "ffmpeg exit code = $?"
		if [[ $? == 0 ]]
		  then
			test -d "$FolderSources" || mkdir -p "$FolderSources"
			mv "$InFile" "$FolderSources/$InFile"
		  fi
	else
	  echo "Нет такого фильтра: $fName, файл $InFile" | tee -a ff-loop.log
	fi
  done
